local set = vim.api.nvim_set_hl
local c = require('night-owls-song.color')

DiagnosticError
DiagnosticWarn
DiagnosticInfo
DiagnosticHint
DiagnosticOk

DiagnosticVirtualTextError
DiagnosticVirtualTextWarn
DiagnosticVirtualTextInfo
DiagnosticVirtualTextHint

DiagnosticUnderlineError
DiagnosticUnderlineWarn
DiagnosticUnderlineInfo
DiagnosticUnderlineHint

DiagnosticFloatingError
DiagnosticFloatingWarn
DiagnosticFloatingInfo
DiagnosticFloatingHint

DiagnosticSignError
DiagnosticSignWarn
DiagnosticSignInfo
DiagnosticSignHint
