return {
    pink             = os.getenv('COLOR_PINK'),
    pink_bright      = os.getenv('COLOR_PINK_BRIGHT'),
    red              = os.getenv('COLOR_RED'),
    red_bright       = os.getenv('COLOR_RED_BRIGHT'),
    orange           = os.getenv('COLOR_ORANGE'),
    orange_bright    = os.getenv('COLOR_ORANGE_BRIGHT'),
    yellow           = os.getenv('COLOR_YELLOW'),
    yellow_bright    = os.getenv('COLOR_YELLOW_BRIGHT'),
    green            = os.getenv('COLOR_GREEN'),
    green_bright     = os.getenv('COLOR_GREEN_BRIGHT'),
    cyan             = os.getenv('COLOR_CYAN'),
    cyan_bright      = os.getenv('COLOR_CYAN_BRIGHT'),
    blue             = os.getenv('COLOR_BLUE'),
    blue_bright      = os.getenv('COLOR_BLUE_BRIGHT'),
    dark_blue        = os.getenv('COLOR_DARK_BLUE'),
    dark_blue_right  = os.getenv('COLOR_DARK_BLUE_RIGHT'),
    purple           = os.getenv('COLOR_PURPLE'),
    purple_bright    = os.getenv('COLOR_PURPLE_BRIGHT'),
    black            = os.getenv('COLOR_BLACK'),
    grey_dark        = os.getenv('COLOR_GREY_DARK'),
    grey             = os.getenv('COLOR_GREY'),
    grey_light       = os.getenv('COLOR_GREY_LIGHT'),
    white            = os.getenv('COLOR_WHITE'),
    comment          = os.getenv('COLOR_COMMENT')
}
